import { FormEvent } from 'react';
import { Link, useForm } from '@inertiajs/react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import AppLayout from '@/layouts/app-layout';

type FormMode = 'create' | 'edit';

type SampleEntityFormPayload = {
    title: string | null;
    body: string | null;
};

type SampleEntityFormPageProps = {
    moduleTitle: string;
    routePath: string;
    mode: FormMode;
    entity: (Record<string, unknown> & { id: number | string }) | null;
};

export default function SampleEntityFormPage({
    moduleTitle,
    routePath,
    mode,
    entity,
}: SampleEntityFormPageProps) {
    const form = useForm<SampleEntityFormPayload>({
        title: '',
        body: null,
    });

    const isEdit = mode === 'edit' && entity !== null;

    const submit = (event: FormEvent<HTMLFormElement>) => {
        event.preventDefault();

        form.transform((data) => data);

        if (isEdit) {
            form.patch(`${routePath}/${String(entity.id)}`);

            return;
        }

        form.post(routePath);
    };

    return (
        <AppLayout>
            <div className="space-y-6 p-4 sm:p-6">
                <Card>
                    <CardHeader>
                        <CardTitle>{isEdit ? `Edit ${moduleTitle}` : `Create ${moduleTitle}`}</CardTitle>
                        <CardDescription>
                            Generated by make:saas-module with tenant-safe defaults.
                        </CardDescription>
                    </CardHeader>
                    <CardContent>
                        <form className="space-y-4" onSubmit={submit}>
                            <div className="space-y-2">
                                <Label htmlFor="title">Title</Label>
                                <Input
                                    id="title"
                                    value={String(form.data.title ?? '')}
                                    onChange={(event) => form.setData('title', event.currentTarget.value)}
                                />
                            </div>
                            <div className="space-y-2">
                                <Label htmlFor="body">Body</Label>
                                <Input
                                    id="body"
                                    value={String(form.data.body ?? '')}
                                    onChange={(event) => form.setData('body', event.currentTarget.value)}
                                />
                            </div>

                            <div className="flex flex-wrap gap-2">
                                <Button type="submit" disabled={form.processing}>
                                    {isEdit ? 'Save changes' : 'Create'}
                                </Button>
                                <Button type="button" variant="outline" asChild>
                                    <Link href={routePath}>Cancel</Link>
                                </Button>
                            </div>
                        </form>
                    </CardContent>
                </Card>
            </div>
        </AppLayout>
    );
}