import { Link } from '@inertiajs/react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import AppLayout from '@/layouts/app-layout';

type ModuleField = {
    name: string;
    label: string;
};

type ModuleItem = Record<string, unknown> & {
    id: number | string;
};

type ModuleIndexPageProps = {
    moduleTitle: string;
    routePath: string;
    fields: ModuleField[];
    items: ModuleItem[];
};

export default function SampleEntityIndexPage({
    moduleTitle,
    routePath,
    fields,
    items,
}: ModuleIndexPageProps) {
    return (
        <AppLayout>
            <div className="space-y-6 p-4 sm:p-6">
                <Card>
                    <CardHeader className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
                        <div>
                            <CardTitle>{moduleTitle}</CardTitle>
                            <CardDescription>Tenant-scoped records generated by Phase 8 DX.</CardDescription>
                        </div>
                        <Button asChild>
                            <Link href={`${routePath}/create`}>Create {moduleTitle}</Link>
                        </Button>
                    </CardHeader>
                </Card>

                <div className="grid gap-4">
                    {items.length === 0 ? (
                        <Card>
                            <CardContent className="py-10 text-sm text-muted-foreground">
                                No records yet.
                            </CardContent>
                        </Card>
                    ) : (
                        items.map((item) => (
                            <Card key={String(item.id)}>
                                <CardHeader className="pb-2">
                                    <CardTitle className="text-base">Record #{String(item.id)}</CardTitle>
                                </CardHeader>
                                <CardContent className="space-y-2">
                                    {fields.map((field) => (
                                        <div key={`${String(item.id)}-${field.name}`} className="text-sm">
                                            <span className="font-medium">{field.label}:</span>{' '}
                                            <span className="text-muted-foreground">
                                                {String(item[field.name] ?? '-')}
                                            </span>
                                        </div>
                                    ))}

                                    <div className="flex flex-wrap gap-2 pt-2">
                                        <Button variant="outline" asChild>
                                            <Link href={`${routePath}/${String(item.id)}`}>View</Link>
                                        </Button>
                                        <Button variant="secondary" asChild>
                                            <Link href={`${routePath}/${String(item.id)}/edit`}>Edit</Link>
                                        </Button>
                                    </div>
                                </CardContent>
                            </Card>
                        ))
                    )}
                </div>
            </div>
        </AppLayout>
    );
}